### ISSUE TITLE
Observability addon configuration

### ISSUE THREAD

**Issue by Azbesciak** [canonical/microk8s-core-addons#125]
Hi, I have just installed the observability addon. I have searched through the deployments and config maps, and tried to find the way out, but failed, so let me ask - how to supply custom Prometheus (alert.rules, prometheus.yml) and alertmanager rules?

Also please notice that this addon is not mentioned on https://microk8s.io/docs/addons (there is a Prometheus addon [obsolete], but url is 404 anyway).

Just wonder if passing own kube-prometheus repo deployment would fix it - just to override, but it is a little overkill IMO, and maybe something microk8s may be overridden?

Thanks.

**Comment by Azbesciak** [comment]
Hello :)? Anything on this?

**Comment by Azbesciak** [comment]
Hellooooo :)

**Comment by kamontat** [comment]
Yes can use `microk8s enable observability -f values.yaml` command to deploy your own custom config.
For `values.yaml` file, you can read more detail on [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).

I assume you familiar with helm chart and values file.

**Comment by Azbesciak** [comment]
@kamontat Ok, thanks but for example, I want to provide custom values for grafana - I suppose it would be in `custom.ini`. Is it somehow possible in other way that during the runtime update the config map? Can I somehow persist the configuration from grafana, to recreate it on other machine when I will make a new microk8s installation?

BTW maybe it is possible to provide some env variables in that `values.yml`?

**Comment by amartincolby** [comment]
I am also wandering by wondering about the current state of observability and best practices around it. What are the current plans because I recently lost my Grafana integration with Linkerd and want to make sure that any methods I implement to solve this don't get broken in the future.

**Comment by amartincolby** [comment]
I ended up abandoning the addon and just installing its constituent parts myself. Ultimately it ended up being better for me.

**Comment by anastazya** [comment]
> I ended up abandoning the addon and just installing its constituent parts myself. Ultimately it ended up being better for me.

Yep, cause without documentation there's no point.

**Comment by davidwincent** [comment]
> Yes can use `microk8s enable observability -f values.yaml` command to deploy your own custom config. For `values.yaml` file, you can read more detail on [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).
> 
> I assume you familiar with helm chart and values file.

This did not work for me:

```console
❯ microk8s enable observability -f helm/values.yaml
Infer repository core for addon observability
Addon core/dns is already enabled
Addon core/helm3 is already enabled
Addon core/hostpath-storage is already enabled
Enabling observability
Unknown option -f

```

**Comment by anastazya** [comment]
> > Yes can use `microk8s enable observability -f values.yaml` command to deploy your own custom config. For `values.yaml` file, you can read more detail on [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).
> > I assume you familiar with helm chart and values file.
> 
> This did not work for me:
> 
> ```
> ❯ microk8s enable observability -f helm/values.yaml
> Infer repository core for addon observability
> Addon core/dns is already enabled
> Addon core/helm3 is already enabled
> Addon core/hostpath-storage is already enabled
> Enabling observability
> Unknown option -f
> ```

Also i DO NOT want 'core/hostpath-storage' addon as i have longhorn distributed storage or other better options. There's no way to do anything useful with this, as it's presented right now.

**Comment by DuyAnhTran95** [comment]
> > Yes can use `microk8s enable observability -f values.yaml` command to deploy your own custom config. For `values.yaml` file, you can read more detail on [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).
> > I assume you familiar with helm chart and values file.
> 
> This did not work for me:
> 
> ```
> ❯ microk8s enable observability -f helm/values.yaml
> Infer repository core for addon observability
> Addon core/dns is already enabled
> Addon core/helm3 is already enabled
> Addon core/hostpath-storage is already enabled
> Enabling observability
> Unknown option -f
> ```

A quick look at the [source code ](https://github.com/canonical/microk8s-core-addons/blob/main/addons/observability/enable) shows me that the correct flag would be `--kube-prometheus-stack-values`. I haven't done any test on that though.

**Comment by danielabbatt** [comment]
> > > Yes can use `microk8s enable observability -f values.yaml` command to deploy your own custom config. For `values.yaml` file, you can read more detail on [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).
> > > I assume you familiar with helm chart and values file.
> > 
> > 
> > This did not work for me:
> > ```
> > ❯ microk8s enable observability -f helm/values.yaml
> > Infer repository core for addon observability
> > Addon core/dns is already enabled
> > Addon core/helm3 is already enabled
> > Addon core/hostpath-storage is already enabled
> > Enabling observability
> > Unknown option -f
> > ```
> 
> A quick look at the [source code ](https://github.com/canonical/microk8s-core-addons/blob/main/addons/observability/enable) shows me that the correct flag would be `--kube-prometheus-stack-values`. I haven't done any test on that though.

Yes this is correct, I had to update my own usage to do this, if you look at the source code, as @DuyAnhTran95 says, you can see there are multiple options now for providing different values files.

**Comment by rodrigo-galba** [comment]
Hi there. To pass custom values to the observability addon, use:
````
microk8s enable observability --kube-prometheus-stack-values=values.yml
````
Later, to get all values from the observability release created by Helm, use:
```
helm get values -n observability kube-prom-stack > prom-values.yaml
```

**Comment by josedgm** [comment]
> Later, to get all values from the observability release created by Helm, use:

And what if you later want to change a value? Do you have to remove and install the addon again while pointing to the updated yaml file?

**Comment by neoaggelos** [comment]
@josedgm An alternative would be to update the helm installation directly. The command should look like this:

```
helm upgrade -n observability kube-prom-stack kube-prometheus-stack \
  --repo https://prometheus-community.github.io/helm-charts \
  --reuse-values -f new_values.yaml
```

Keep in mind that the intent of the addon is to simply make it easy to deploy the stack, not handle lifecycle and further operations.

**Comment by filip-franek** [comment]
On top of what was mentioned above how about patching the current deployment?

Here is an example of how I patched my  Grafana deployment to mount the Grafana data location to my persistent volume. I have it applied over Flux or it could be applied over `kubectl apply -f  grafana.yml`. It assumes the Grafana Persistent Volume Claim (PVC) is already created.

```yaml
# grafana.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prom-stack-grafana
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prom-stack
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kube-prom-stack
        app.kubernetes.io/name: grafana
    spec:
      containers:
      - name: grafana
        volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: <storage-class>
      volumes:
      - name: <storage-class>
        persistentVolumeClaim:
          claimName: <grafana-pvc>
```

There is also a [question](https://github.com/prometheus-operator/kube-prometheus/discussions/2287) posted on kube-prometheus discussion board (with no answers so far) regarding how to integrate the [Grafana Operator](https://github.com/grafana/grafana-operator) in the stack which would also be another way how to manage Grafana. The [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) is in the kube-prometheus stack already unlike the Grafana Operator to manage Prometheus.

Here is an example of how to change the Prometheus configuration for scraping metrics and its storage with the Prometheus Operator. It also assumes the Prometheus Persistent Volume Claim (PVC) is already created.

```yaml
# prometheus-cr-patch.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prom-stack-kube-prome-prometheus
  namespace: observability
spec:
  scrapeInterval: "120s"
  evaluationInterval: "120s" 
  retention: "15d"
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: <storage-class>
        resources:
          requests:
            storage: 15Gi
```
