### ISSUE TITLE
No Resource requests for addons

### ISSUE THREAD

**Issue by jniclas** [canonical/microk8s-core-addons#223]
#### Summary

Hey, I am new to microk8s and after deploying a 3-mode cluster and enabling cert-manager, server-metrics, ingress and dns, I only found resource requests in the coredns service, but not on ingress, cert-manager and server-metrics. 
Is this by design, or do I have to enable the addons with an extra yaml, that specifies resource requests and limits? 

#### Why is this important?

It would be important to manage the resources properly, especially when the cluster uses a lot of addons.

#### Are you interested in contributing to this feature?

maybe, did not do that for until now.

**Comment by ktsakalozos** [comment]
Hi @jniclas, welcome to k8s. What do you mean by "resource requests"? Can you give me an example of what kind of manageable resources you have for coredns?

**Comment by jniclas** [comment]
of course, when I output the coredns values, the service, enabled by `microk8s enable dns` I get values:
```yaml
containers:
  - name: coredns
    image: coredns/coredns:1.10.0
    ...
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
```
But cert-manager has values:
```yaml
containers:
  - name: cert-manager
    image: quay.io/jetstack/cert-manager-webhook:v1.8.0
    ...
    resources: {}
```
