### ISSUE TITLE
microk8s enable metallb does not accept ipv6 input

### ISSUE THREAD

**Issue by vosdev** [canonical/microk8s-core-addons#245]
#### Summary
```
Name      Version   Rev    Tracking       Publisher   Notes
core20    20230801  2015   latest/stable  canonical✓  base
microk8s  v1.28.2   6085   1.28/stable    canonical✓  classic
snapd     2.60.4    20290  latest/stable  canonical✓  snapd
```
Enablin the metallb addon with a ipv6 cidr says it's invalid. 
`Your input value (2001:db8::252:252:252:1-2001:db8:1:252:252:252:252) is not a valid IP Range`

Metallb works with dualstack if you supply it a ipv6 cidr manually:
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.220-10.0.1.229
  - 2001:db8::252:252:252:1-2001:db8:1:252:252:252:252
  ```

```
k get svc example-service
NAME              TYPE           CLUSTER-IP       EXTERNAL-IP                                 PORT(S)        AGE
example-service   LoadBalancer   10.252.252.160   10.0.1.220,2001:db8::1:252:252:252:1        80:32481/TCP   24m
```

#### What Should Happen Instead?

Accept the valid ipv6 range

#### Reproduction Steps

(replaced my ipv6 cidr with 2001:db8 )
1. microk8s enable metallb
2. include ipv6 in your input like so: `10.0.1.220-10.0.1.229,2001:db8::252:252:252:1-2001:db8:1:252:252:252:252` 
```
# microk8s enable metallb
Infer repository core for addon metallb
Enabling MetalLB
Enter each IP address range delimited by comma (e.g. '10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111'): 10.0.1.220-10.0.1.229,2001:db8::252:252:252:1-2001:db8:1:252:252:252:252
Your input value (2001:db8::252:252:252:1-2001:db8:1:252:252:252:252) is not a valid IP Range
```

#### Can you suggest a fix?

https://github.com/canonical/microk8s-core-addons/blob/main/addons/metallb/enable#L33

These Regex are only for IPv4. They should also accept ipv6.

Furthermore I think the `microk8s enable metallb:192.168.1.0/24` syntax should no longer use a `:`, but switch to a `=` to make syntax easier for ipv6 support.

#### Are you interested in contributing with a fix?

unfortunately no
