### ISSUE TITLE
[Cert-manager]  Wait for cert-manager to be fully ready

### ISSUE THREAD

**Issue by balchua** [canonical/microk8s-core-addons#82]
#### Summary

Make sure when the cert-manager addon completes, the cert-manager is ready to accept certificate requests.  What do you think?
Waiting for the pods to be in `Ready` state is not enough.  We need to try creating resources, to make sure cert-manager is fully ready.

Example by applying the yaml below, the user will know that it is ready to serve certificate requests.

``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
```

#### Why is this important?

Some addons require cert-managers to be available and ready.  For example Jaeger v1.31+.

#### Are you interested in contributing to this feature?

yes

What do you think about this?
