### ISSUE TITLE
hostpath-storage ignores pvDir

### ISSUE THREAD

**Issue by sHaggYcaT** [canonical/microk8s-core-addons#94]
#### Summary

default clean installation via snap: ``microk8s  v1.24.3 ``

hostpath-storage ignores pvDir, if we create a custom StorageClass, Example:

```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nvme
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/storage/nvme/storage
volumeBindingMode: WaitForFirstConsumer
```

```bash
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
pvc-a01196ef-01ed-4055-b1b8-23c1ccb9d1bd   8Gi        RWO            Delete           Bound    default/wiki-dokuwiki   nvme                    11s

kubectl describe pv pvc-a01196ef-01ed-4055-b1b8-23c1ccb9d1bd
Name:              pvc-a01196ef-01ed-4055-b1b8-23c1ccb9d1bd
Labels:            <none>
Annotations:       hostPathProvisionerIdentity: microk8s
                   pv.kubernetes.io/provisioned-by: microk8s.io/hostpath
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      nvme
Status:            Bound
Claim:             default/wiki-dokuwiki
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          8Gi
Node Affinity:     
  Required Terms:  
    Term 0:        kubernetes.io/hostname in [microk8s]
Message:           
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/snap/microk8s/common/default-storage/default-wiki-dokuwiki-pvc-a01196ef-01ed-4055-b1b8-23c1ccb9d1bd
    HostPathType:  DirectoryOrCreate
Events:            <none>

```
#### What Should Happen Instead?

I expected creation of the PVC in the another file system
